name: run test of feature branches

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run tests
        run: python test.py
