name: run test of feature branches

on:
  push:
    branches:
      '**'
jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/setup-python@v6
        with: 
          python-version: '3.12'

      - name: run test
        run:  python test.py
      
    
